# Generated by Django 2.0.5 on 2020-06-09 16:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enggperformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engg_id', models.IntegerField(blank=True, null=True)),
                ('calls_closed', models.IntegerField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=20, null=True)),
                ('total_distance_travelled', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tickets', models.FileField(blank=True, null=True, upload_to='')),
                ('total_ticket_amnt', models.IntegerField(blank=True, null=True)),
                ('battery_percentage', models.IntegerField(blank=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('punchin_time', models.TimeField(blank=True, null=True)),
                ('punchout_time', models.TimeField(blank=True, null=True)),
                ('online_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_open', models.IntegerField(blank=True, null=True)),
                ('total_closed', models.IntegerField(blank=True, null=True)),
                ('total_pending', models.IntegerField(blank=True, null=True)),
                ('stars', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, null=True)),
                ('product_size', models.CharField(max_length=20, null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_code', models.IntegerField(null=True)),
                ('product_recieved_date', models.DateField(null=True)),
                ('product_provider_name', models.CharField(max_length=20, null=True)),
                ('Total_product_quantity', models.IntegerField(null=True)),
                ('product_serial_no', models.IntegerField(null=True)),
                ('product_model', models.CharField(max_length=20, null=True)),
                ('product_model_id', models.IntegerField(null=True)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('product_warranty', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='cust_ratings',
            new_name='battery_percentage',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='comp_name',
            new_name='comp_feedback',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='comp_problem',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='call_alloc_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='call_images_uploaded',
            new_name='engg_bus_ticket_pic',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='eng_name',
            new_name='engg_complaint_note',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='part_name',
            new_name='engg_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_area',
            new_name='customer_adrress',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_compay_type',
            new_name='customer_company_type',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='call_alloc_engg_name',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='call_alloc_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='call_auto_close_date',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='call_closed_date',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='call_prioriy',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_call_end_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_call_start_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_job_end_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_job_start_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_latitude',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_longitude',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_probelm_solve_msg',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_delivery_date',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_pickup_date',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_warranty',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_agreement',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_compy_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_landmark',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_product1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_product2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_product3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_product4',
        ),
        migrations.AddField(
            model_name='callallocate',
            name='call_priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='client_sign_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/sign/'),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='comp_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginapp.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_bike_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_bus_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_bus_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_client_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_end_reading',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_end_reading_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_long',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_part_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_part_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_part_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/part/'),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_solve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_start_reading',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_start_reading_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_ticket_amnt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_total_distance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_transport_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engineer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coadmin',
            name='co_status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=12, null=True, verbose_name=' Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_GSTIN_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="GSTIN number must be entered in the format: '999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_agreement_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_agreement_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engg',
            name='battery_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engg',
            name='complaint_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='engg',
            name='engg_lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='engg',
            name='engg_long',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(null=True, upload_to='co_pic/profile/', verbose_name='Engineer photo *'),
        ),
        migrations.AddField(
            model_name='engg',
            name='engg_status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default=1, max_length=12, null=True, verbose_name='Engineer Status'),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='call_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Open', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='call_type',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Networking', 'Networking'), ('Software', 'Software')], default='Hardware', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='complaint_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginapp.engg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_status',
            field=models.CharField(blank=True, choices=[('Engineer Assign', 'Engineer Assign'), ('Left for site', 'Left for site'), ('Left from site', 'Left from site'), ('Reached at site', 'Reached at site')], default='Engineer Assign', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='branch_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_bdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_city',
            field=models.CharField(max_length=70, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_conf_pass',
            field=models.CharField(blank=True, default='amc@123', max_length=16, null=True, verbose_name='Confirm Password'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_designation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_email',
            field=models.EmailField(max_length=70, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_joining_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_pass',
            field=models.CharField(blank=True, default='amc@123', max_length=16, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_qual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='contact_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='tell_no',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_doc',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_address',
            field=models.TextField(null=True, verbose_name='Engineer Address'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Engineer Age'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_bdate',
            field=models.DateField(blank=True, null=True, verbose_name='Engineer Birth Date'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_branch_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Engineer Branch Code'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_city',
            field=models.CharField(max_length=70, null=True, verbose_name='Engineer City'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_conf_pass',
            field=models.CharField(default='amc@123', max_length=16, null=True, verbose_name='Engineer Confirm Password'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_contact_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Engineer Contact Number'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_designation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Engineer Designation'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_email',
            field=models.EmailField(max_length=70, null=True, verbose_name='Engineer E-mail id'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=12, null=True, verbose_name='Engineer Gender'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Engineer id *'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Engineer Joining Date'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Engineer Name *'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pass',
            field=models.CharField(default='amc@123', max_length=16, null=True, verbose_name='Engineer Password'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Engineer Permanent Address'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_qual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Engineer Qualification'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_skill',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Networking', 'Networking'), ('Software', 'Software')], default=1, max_length=20, null=True, verbose_name='Engineer Skill'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_tell_no',
            field=models.CharField(blank=True, max_length=17, verbose_name='Engineer Telephone Number'),
        ),
        migrations.AddField(
            model_name='performance',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.engg'),
        ),
    ]
