# Generated by Django 2.0.3 on 2018-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='callallocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100)),
                ('co_name', models.CharField(max_length=200)),
                ('co_address', models.TextField()),
                ('co_email', models.CharField(max_length=200)),
                ('co_contact', models.IntegerField()),
                ('co_problem', models.TextField()),
                ('call_alloc', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
