# Generated by Django 2.0.4 on 2018-04-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_remove_customer_customer_compy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='enggperformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls_closed', models.IntegerField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=20, null=True)),
                ('total_distance_travelled', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tickets', models.FileField(blank=True, null=True, upload_to='')),
                ('total_ticket_amnt', models.IntegerField(blank=True, null=True)),
                ('battery_percentage', models.IntegerField(blank=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='enggperformance',
            name='engg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.engg'),
        ),
    ]
