# Generated by Django 2.0.2 on 2018-03-15 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20180307_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='coadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_id', models.IntegerField()),
                ('co_name', models.CharField(max_length=200)),
                ('co_address', models.TextField()),
                ('co_email', models.EmailField(max_length=70)),
                ('contact_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('tell_no', models.IntegerField(blank=True)),
                ('co_city', models.CharField(max_length=70)),
                ('branch_code', models.CharField(max_length=100)),
                ('co_gender', models.CharField(max_length=6)),
                ('co_bdate', models.DateField()),
                ('co_age', models.IntegerField()),
                ('co_joining_date', models.DateField()),
                ('co_qual', models.CharField(max_length=50)),
                ('co_designation', models.CharField(max_length=50)),
                ('co_photo', models.ImageField(upload_to='co_pic/')),
                ('co_pass', models.CharField(max_length=16)),
                ('co_conf_pass', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='co_address',
            new_name='comp_address',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='co_email',
            new_name='comp_email',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='co_name',
            new_name='comp_name',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='co_problem',
            new_name='comp_problem',
        ),
    ]
