# Generated by Django 2.0.4 on 2018-04-05 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0003_auto_20180315_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coadmin',
            name='co_id',
        ),
        migrations.RemoveField(
            model_name='coadmin',
            name='co_photo',
        ),
        migrations.AddField(
            model_name='coadmin',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_bdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='tell_no',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
