# Generated by Django 2.0.4 on 2018-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20180420_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='enggperformance',
            name='online_status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enggperformance',
            name='punchin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enggperformance',
            name='punchout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
