# Generated by Django 2.0.4 on 2018-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20180405_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coadmin',
            name='co_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
