# Generated by Django 2.0.4 on 2018-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20180421_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
    ]
