# Generated by Django 2.0.4 on 2018-05-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_auto_20180429_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callallocate',
            name='eng_name',
        ),
        migrations.AddField(
            model_name='callallocate',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_pic/'),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='client_sign_image',
            field=models.ImageField(blank=True, null=True, upload_to='sign_pic/'),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='part_apply_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='part_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='part_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=12, null=True),
        ),
    ]
