# Generated by Django 2.0.4 on 2018-05-06 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20180503_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='call_alloc_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='call_closed_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
