# Generated by Django 2.0.4 on 2018-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_auto_20180506_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='call_status',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=7, null=True),
        ),
    ]
