# Generated by Django 2.0.5 on 2018-05-09 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_auto_20180506_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='call_closed_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
