# Generated by Django 2.0.5 on 2018-05-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_auto_20180509_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callallocate',
            name='call_closed_date',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='call_images_uploaded',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='client_image',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='client_sign_image',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='cust_ratings',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_call_end_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_call_start_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_feedback',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_job_end_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_job_start_time',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_latitude',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_longitude',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_probelm_solve_msg',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_rating',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_status',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_apply_date',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_delivery_date',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_description',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_pickup_date',
        ),
        migrations.RemoveField(
            model_name='callallocate',
            name='part_warranty',
        ),
    ]
