# Generated by Django 2.0.5 on 2018-05-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0013_callallocate_engg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callallocate',
            name='call_alloc_engg_name',
        ),
    ]
