# Generated by Django 2.0.5 on 2018-05-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0014_remove_callallocate_call_alloc_engg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callallocate',
            old_name='comp_problem',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='call_auto_close_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='call_alloc_date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='callallocate',
            old_name='comp_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='call_status',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=12, null=True),
        ),
    ]
