# Generated by Django 2.0.5 on 2018-05-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0016_auto_20180512_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enggperformance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='enggperformance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
