# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0017_auto_20180512_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='engg',
            name='engg_status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default=1, max_length=12, null=True),
        ),
    ]
