# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0018_engg_engg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='call_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default=1, max_length=7, null=True),
        ),
    ]
