# Generated by Django 2.0.5 on 2018-05-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0021_auto_20180516_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='engg_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
