# Generated by Django 2.0.5 on 2018-05-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0022_callallocate_engg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callallocate',
            name='complaint_no',
        ),
    ]
