# Generated by Django 2.0.5 on 2018-05-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0023_remove_callallocate_complaint_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='engg_name',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
