# Generated by Django 2.0.5 on 2018-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0024_auto_20180520_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20, null=True)),
                ('product_size', models.CharField(blank=True, max_length=20, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_code', models.IntegerField(blank=True, null=True)),
                ('product_recieved_date', models.DateField(blank=True, null=True)),
                ('product_provider_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Total_product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_serial_no', models.IntegerField(blank=True, null=True)),
                ('product_model', models.CharField(blank=True, max_length=20, null=True)),
                ('product_model_id', models.IntegerField(blank=True, null=True)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('product_warranty', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
