# Generated by Django 2.0.5 on 2018-05-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0027_engg_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coadmin',
            name='author',
        ),
        migrations.RemoveField(
            model_name='engg',
            name='author',
        ),
    ]
