# Generated by Django 2.0.5 on 2018-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0028_auto_20180524_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engg',
            name='engg_bdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
