# Generated by Django 2.0.5 on 2018-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0031_auto_20180526_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='call_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Offline', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='call_type',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Networking', 'Networking'), ('Software', 'Software')], default='Hardware', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(blank=True, null=True, upload_to='loginapp.ConsolePicture/bytes/filename/mimetype'),
        ),
    ]
