# Generated by Django 2.0.5 on 2018-05-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0032_auto_20180526_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='product',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Networking', 'Networking'), ('Software', 'Software')], default='Desktop PC', max_length=100, null=True),
        ),
    ]
