# Generated by Django 2.0.5 on 2018-05-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0033_auto_20180526_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='product',
            field=models.CharField(blank=True, choices=[('Desktop PC', 'Desktop PC'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Projector', 'Projector'), ('UPS', 'UPS'), ('Scanner', 'Scanner'), ('Switch', 'Switch'), ('Server', 'Server'), ('N-Computing', 'N-Computing'), ('Invertor', 'Invertor'), ('Patch Panel', 'Patch Panel'), ('Plasma TV', 'Plasma TV'), ('LAN', 'LAN'), ('Thin Client', 'Thin Client'), ('Work Station', 'Work Station'), ('Plotter', 'Plotter'), ('CCTV', 'CCTV'), ('USB Camera', 'USB Camera'), ('VC Device', 'VC Device'), ('Remote', 'Remote')], default='Desktop PC', max_length=100, null=True),
        ),
    ]
