# Generated by Django 2.0.5 on 2018-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0034_auto_20180526_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='call_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Open', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='enggperformance',
            name='engg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
