# Generated by Django 2.0.5 on 2018-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0036_auto_20180529_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='complaint_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
