# Generated by Django 2.0.5 on 2018-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0037_callallocate_complaint_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
