# Generated by Django 2.0.5 on 2018-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0039_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='engg_status',
            field=models.CharField(blank=True, choices=[('Engineer Assign', 'Engineer Assign'), ('Left for site', 'Left for site'), ('Left from site', 'Left from site'), ('Reached at site', 'Reached at site')], default='Engineer Assign', max_length=100, null=True),
        ),
    ]
