# Generated by Django 2.0.5 on 2018-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0043_auto_20180604_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_product1',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Desktop PC', max_length=50, null=True),
        ),
    ]
