# Generated by Django 2.0.5 on 2018-06-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0044_auto_20180604_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsolePicture',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
