# Generated by Django 2.0.5 on 2018-06-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0045_auto_20180612_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_product2',
            new_name='customer_product',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_product1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_product3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_product4',
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
    ]
