# Generated by Django 2.0.5 on 2018-06-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0046_auto_20180612_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='engg_bike_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
