# Generated by Django 2.0.5 on 2018-06-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0047_callallocate_engg_bike_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_doc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
