# Generated by Django 2.0.5 on 2018-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0048_auto_20180613_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='engg_part_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_part_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='call_priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='client_sign_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic'),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_client_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_part_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
