# Generated by Django 2.0.5 on 2018-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0050_auto_20180618_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='comp_feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='comp_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
