# Generated by Django 2.0.5 on 2018-06-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0051_auto_20180618_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='comp_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
