# Generated by Django 2.0.6 on 2018-06-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0053_auto_20180618_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='engg_part_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
