# Generated by Django 2.0.5 on 2018-06-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0054_auto_20180619_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_area',
            new_name='customer_adrress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_landmark',
        ),
    ]
