# Generated by Django 2.0.6 on 2018-06-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0055_auto_20180622_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='engg_end_reading',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_start_reading',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic\\'),
        ),
    ]
