# Generated by Django 2.0.6 on 2018-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0056_auto_20180627_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='engg_bus_ticket_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
    ]
