# Generated by Django 2.0.6 on 2018-06-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0057_callallocate_engg_bus_ticket_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='engg_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
