# Generated by Django 2.0.6 on 2018-07-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0060_auto_20180705_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='complaint_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
