# Generated by Django 2.0.6 on 2018-07-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0061_auto_20180706_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_open', models.IntegerField(blank=True, null=True)),
                ('total_closed', models.IntegerField(blank=True, null=True)),
                ('total_pending', models.IntegerField(blank=True, null=True)),
                ('stars', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.engg')),
            ],
        ),
    ]
