# Generated by Django 2.0.6 on 2018-07-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0062_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_compay_type',
            new_name='customer_company_type',
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='client_sign_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/sign/'),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_part_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/part/'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/profile/'),
        ),
    ]
