# Generated by Django 2.0.6 on 2018-07-08 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0063_auto_20180707_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginapp.customer'),
            preserve_default=False,
        ),
    ]
