# Generated by Django 2.0.6 on 2018-07-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0064_callallocate_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='engg_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='loginapp.engg'),
            preserve_default=False,
        ),
    ]
