# Generated by Django 2.0.6 on 2018-07-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0065_auto_20180708_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='engg_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
