# Generated by Django 2.0.6 on 2018-07-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0066_auto_20180708_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callallocate',
            old_name='engg_id',
            new_name='engineer_id',
        ),
    ]
