# Generated by Django 2.0.6 on 2018-07-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0067_auto_20180708_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='start',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
