# Generated by Django 2.0.6 on 2018-07-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0068_auto_20180709_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
