# Generated by Django 2.0.6 on 2018-07-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0070_auto_20180710_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callallocate',
            name='engineer_id',
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='loginapp.engg'),
            preserve_default=False,
        ),
    ]
