# Generated by Django 2.0.6 on 2018-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0071_auto_20180710_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='engineer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
