# Generated by Django 2.0.6 on 2018-07-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0072_callallocate_engineer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callallocate',
            name='engineer_id',
        ),
    ]
