# Generated by Django 2.0.6 on 2018-07-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0073_remove_callallocate_engineer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callallocate',
            name='engg_id',
        ),
    ]
