# Generated by Django 2.0.6 on 2018-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0075_auto_20180711_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='battery_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='call_alloc_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='call_tat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='caller_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='comp_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='comp_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='complaint_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='cust_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='branch_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_city',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_conf_pass',
            field=models.CharField(blank=True, default='dcc@123', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_pass',
            field=models.CharField(blank=True, default='dcc@123', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_branch_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_city',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_conf_pass',
            field=models.CharField(default='dcc@123', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pass',
            field=models.CharField(default='dcc@123', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(null=True, upload_to='co_pic/profile/'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_skill',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Networking', 'Networking'), ('Software', 'Software')], default=1, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Total_product_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_model_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_provider_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_recieved_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_serial_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_warranty',
            field=models.IntegerField(null=True),
        ),
    ]
