# Generated by Django 2.0.6 on 2018-07-11 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0076_auto_20180711_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='coadmin',
            name='co_status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default=1, max_length=12, null=True, verbose_name=' Status'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='branch_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_bdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_city',
            field=models.CharField(max_length=70, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_conf_pass',
            field=models.CharField(blank=True, default='dcc@123', max_length=16, null=True, verbose_name='Confirm Password'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_designation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_email',
            field=models.EmailField(max_length=70, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_joining_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_pass',
            field=models.CharField(blank=True, default='dcc@123', max_length=16, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_qual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='contact_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='tell_no',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_address',
            field=models.TextField(null=True, verbose_name='Engineer Address'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Engineer Age'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_bdate',
            field=models.DateField(blank=True, null=True, verbose_name='Engineer Birth Date'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_branch_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Engineer Branch Code'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_city',
            field=models.CharField(max_length=70, null=True, verbose_name='Engineer City'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_conf_pass',
            field=models.CharField(default='dcc@123', max_length=16, null=True, verbose_name='Engineer Confirm Password'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_contact_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Engineer Contact Number'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_designation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Engineer Designation'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_email',
            field=models.EmailField(max_length=70, null=True, verbose_name='Engineer E-mail id'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=12, null=True, verbose_name='Engineer Gender'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_id',
            field=models.IntegerField(null=True, verbose_name='Engineer id'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Engineer Joining Date'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Engineer Name'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pass',
            field=models.CharField(default='dcc@123', max_length=16, null=True, verbose_name='Engineer Password'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Engineer Permanent Address'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_pic',
            field=models.ImageField(null=True, upload_to='co_pic/profile/', verbose_name='Engineer photo'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_qual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Engineer Qualification'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_skill',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Networking', 'Networking'), ('Software', 'Software')], default=1, max_length=20, null=True, verbose_name='Engineer Skill'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default=1, max_length=12, null=True, verbose_name='Engineer Status'),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_tell_no',
            field=models.CharField(blank=True, max_length=17, verbose_name='Engineer Telephone Number'),
        ),
    ]
