# Generated by Django 2.0.6 on 2018-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0077_auto_20180711_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='engg',
            name='battery_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engg',
            name='complaint_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='engg',
            name='engg_lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='engg',
            name='engg_long',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
