# Generated by Django 2.0.6 on 2018-07-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0078_auto_20180713_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_agreement',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_agreement_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_agreement_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
