# Generated by Django 2.0.6 on 2018-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0079_auto_20180713_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_doc',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
