# Generated by Django 2.0.6 on 2018-07-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0080_auto_20180713_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callallocate',
            name='call_alloc_time',
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
