# Generated by Django 2.0.6 on 2018-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0081_auto_20180713_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='engg_end_reading_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AddField(
            model_name='callallocate',
            name='engg_start_reading_pic',
            field=models.ImageField(blank=True, null=True, upload_to='co_pic/'),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_end_reading',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_start_reading',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engg',
            name='engg_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Engineer id'),
        ),
    ]
