# Generated by Django 2.0.6 on 2018-07-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0082_auto_20180713_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='call_tat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='caller_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='comp_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='comp_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='complaint_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='cust_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='engg_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='callallocate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
