# Generated by Django 2.0.6 on 2018-07-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0083_auto_20180714_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocate',
            name='engineer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='co_status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=12, null=True, verbose_name=' Status'),
        ),
    ]
