# Generated by Django 2.0.6 on 2018-07-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0084_auto_20180714_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocate',
            name='engg_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
